apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  containers:
    - name: frontend
      image: frontend:1.0
      imagePullPolicy: Never
      ports:
        - containerPort: 80
          name: http
